'use client';
import Categories from "../categories";

export default function () {
  const items = [
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 0,
    },
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 1,
    },
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 2,
    },
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 3,
    },
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 4,
    },
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 5,
    },
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 6,
    },
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 7,
    },
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 8,
    },
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 9,
    },
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 10,
    },
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 11,
    },
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 12,
    },
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 13,
    },
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 14,
    },
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 15,
    },
    {
      imageSource: "/air-force.png",
      imageWidth: 250,
      imageHeight: 250,
      title: "Nike Air Force 1 '07 trainers in triple white",
      price: "109.95 $",
      id: 16,
    },
  ];
  const clothesCategory = {
    title: "All Clothes",
    category1: "T-Shirts",
    category2: "Hoodies",
    category3: "Jeans",
    category4: "Jackets",
    items: items,
  };
  const shoesCategory = {
    title: "All Shoes",
    category1: "Adidas",
    category2: "Nike",
    category3: "New Balance",
    category4: "Vans",
    items: items,
  };
  return <Categories category={shoesCategory}/>;
}
